server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC

#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .html
#
#  resources:
#    static-locations: classpath:/static/



#swagger的相关配置
  swagger:
# 扫描的包路径,默认扫描所有
    base-package: com.example.demo.controller
 # 默认为 true
    enabled: true
    description: 这是一个测试的接口管理
    contact:
      name: BigJ
      email: 805205759@qq.com
    version: v1.0.0
#全局参数,比如Token之类的验证信息可以全局话配置
  global-operation-parameters:
  - description: 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE1NTg4OTMyNDEsInVzZXJuYW1lIjoiYWRtaW4ifQ.Y8y1w3qpnVF3m-4adFLd-smzxl_XWWqlwjj-rn4LzrF64p8u08qzlwb9TysHUiJ_cftVPLoKA8pFqxkuDvndMA'
    modelRef: 'string'
    name: 'Authorization'
    parameter-type: 'header'
    required: false

#逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 删除
      logic-not-delete-value: 0 # 正常
